#### This notebook will guide you through the code behind vits(https://github.com/jaywalnut310/vits),a classical e2e TTS model.

#### Import required package

In [1]:
import os
import json
import argparse
import itertools
import math
import logging
import json
import subprocess
import re
from unidecode import unidecode
from phonemizer import phonemize
import numpy as np
from scipy.io.wavfile import read
import torch
from torch import nn, optim
from torch.nn import functional as F
from torch.utils.data import DataLoader
import random
import librosa
import librosa.util as librosa_util
from librosa.util import normalize, pad_center, tiny
from scipy.signal import get_window
from scipy.io.wavfile import read
from librosa.filters import mel as librosa_mel_fn

c:\Users\linka\anaconda3\envs\pytorch\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\Users\linka\anaconda3\envs\pytorch\lib\site-packages\numpy\.libs\libopenblas.GK7GX5KEQ4F6UYO3P26ULGBQYHGQO7J4.gfortran-win_amd64.dll
c:\Users\linka\anaconda3\envs\pytorch\lib\site-packages\numpy\.libs\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


#### In a e2e TTS system, the first thing is to understand the training data.
##### the training data of VITS consists of two ingredients, text and coresponding audio.

VITS reads data through a txt. Inside the txt, the data is seened as below.

DUMMY1/LJ050-0234.wav|It has used...

DUMMY1/LJ019-0373.wav|to avail himself...

Lets dive into how VITS clean and preprocess the data.

In [2]:
# Some text processing variables.
# No need to understand when you first time see them.
# You will understand what they mean in the following cells.
_pad        = '_'
_punctuation = ';:,.!?¡¿—…"«»“” '
_letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
_letters_ipa = "ɑɐɒæɓʙβɔɕçɗɖðʤəɘɚɛɜɝɞɟʄɡɠɢʛɦɧħɥʜɨɪʝɭɬɫɮʟɱɯɰŋɳɲɴøɵɸθœɶʘɹɺɾɻʀʁɽʂʃʈʧʉʊʋⱱʌɣɤʍχʎʏʑʐʒʔʡʕʢǀǁǂǃˈˌːˑʼʴʰʱʲʷˠˤ˞↓↑→↗↘'̩'ᵻ"
# Export all symbols:
symbols = [_pad] + list(_punctuation) + list(_letters) + list(_letters_ipa)
# Special symbol ids
SPACE_ID = symbols.index(" ")

In [3]:
# Cleaner of text
# For a deep understanding of what the function means
# open cleaner.ipynb
# Regular expression matching whitespace:
_whitespace_re = re.compile(r'\s+')

# List of (regular expression, replacement) pairs for abbreviations:
_abbreviations = [(re.compile('\\b%s\\.' % x[0], re.IGNORECASE), x[1]) for x in [
  ('mrs', 'misess'),
  ('mr', 'mister'),
  ('dr', 'doctor'),
  ('st', 'saint'),
  ('co', 'company'),
  ('jr', 'junior'),
  ('maj', 'major'),
  ('gen', 'general'),
  ('drs', 'doctors'),
  ('rev', 'reverend'),
  ('lt', 'lieutenant'),
  ('hon', 'honorable'),
  ('sgt', 'sergeant'),
  ('capt', 'captain'),
  ('esq', 'esquire'),
  ('ltd', 'limited'),
  ('col', 'colonel'),
  ('ft', 'fort'),
]]
def expand_abbreviations(text):
  for regex, replacement in _abbreviations:
    text = re.sub(regex, replacement, text)
  return text


def lowercase(text):
  return text.lower()


def collapse_whitespace(text):
  return re.sub(_whitespace_re, ' ', text)


def convert_to_ascii(text):
  return unidecode(text)


def english_cleaners2(text):
  '''Pipeline for English text, including abbreviation expansion. + punctuation + stress'''
  text = convert_to_ascii(text)
  text = lowercase(text)
  text = expand_abbreviations(text)
  phonemes = phonemize(text, language='en-us', backend='espeak', strip=True, preserve_punctuation=True, with_stress=True)
  phonemes = collapse_whitespace(phonemes)
  return phonemes

In [4]:
mel_basis = {}
# https://en.wikipedia.org/wiki/Hann_function
hann_window = {}
_symbol_to_id = {s: i for i, s in enumerate(symbols)}
_id_to_symbol = {i: s for i, s in enumerate(symbols)}

# For a closer look at the function, open the file dataset.ipynb
class TextAudioLoader(torch.utils.data.Dataset): 
    # This is the class that loads the data in VITS.
    def __init__(self, audiopaths_and_text):
        # hyperparams and data paths
        # no need to fully understand the init method.
        ###### I substitude hparams(hyper parameters) for a better understanding, the right sides are exactly the same as hparams json file in VITS ######
        self.audiopaths_and_text = audiopaths_and_text
        self.text_cleaners  = ['english_cleaners2']
        self.max_wav_value  = 32768.0
        self.sampling_rate  = 22050
        self.filter_length  = 1024
        self.hop_length     = 256
        self.win_length     = 1024

       # self.cleaned_text = getattr(hparams, "cleaned_text", False)

       # self.add_blank = hparams.add_blank
       # self.min_text_len = getattr(hparams, "min_text_len", 1)
       # self.max_text_len = getattr(hparams, "max_text_len", 190)

        random.seed(1234)
        random.shuffle(self.audiopaths_and_text)
        # self._filter()
    """
    _filter is not needed in tutorial. self.lengths is not used in VITS.
    def _filter(self):
        # The below comment is from original repo
        # Filter text & store spec lengths
        
        # Store spectrogram lengths for Bucketing
        # wav_length ~= file_size / (wav_channels * Bytes per dim) = file_size / (1 * 2)
        # spec_length = wav_length // hop_length
        
        audiopaths_and_text_new = []
        lengths = []
        for audiopath, text in self.audiopaths_and_text:
            # we filter the text with appropriate length
            if self.min_text_len <= len(text) and len(text) <= self.max_text_len:
                audiopaths_and_text_new.append([audiopath, text])
                # lengths store the length of spectrogram
                # length of spectrogram is length of audio // hop_length
                lengths.append(os.path.getsize(audiopath) // (2 * self.hop_length))
        self.audiopaths_and_text = audiopaths_and_text_new
        self.lengths = lengths
    """
    # A method that call get_text and get_audio, return text, spectrogram, and audio(frequency domain).
    def get_audio_text_pair(self, audiopath_and_text):
        # separate filename and text
        audiopath, text = audiopath_and_text[0], audiopath_and_text[1]
        text = self.get_text(text)
        spec, wav = self.get_audio(audiopath)
        return (text, spec, wav)
    
    def get_audio(self, filename):
        audio, sampling_rate = load_wav_to_torch(filename) # read audio.
    
        #if sampling_rate != self.sampling_rate:
        #    raise ValueError("{} {} SR doesn't match target {} SR".format(
        #        sampling_rate, self.sampling_rate))

        audio_norm = audio / self.max_wav_value # normalize
        audio_norm = audio_norm.unsqueeze(0) # add channel
        #spec filename should be the same with audio, with .spec.pt
        spec_filename = filename.replace(".wav", ".spec.pt") 
        if os.path.exists(spec_filename): # skip if already exists
            spec = torch.load(spec_filename)
        else:
            spec = spectrogram_torch(audio_norm, self.filter_length,
                self.sampling_rate, self.hop_length, self.win_length,
                center=False) # read spectrogram from audio, method is at below.
            spec = torch.squeeze(spec, 0)
            torch.save(spec, spec_filename) # save as .spec.pt
        return spec, audio_norm
    def get_text(self, text):
#        if self.cleaned_text:
#            text_norm = cleaned_text_to_sequence(text)
#        else:
        
        text_norm = text_to_sequence(text, self.text_cleaners)
        
        # After cleaning, the text should be looked from    #
        # Mrs. De Mohrenschildt thought that Oswald,        #
        # to
        # mɪsˈɛs də mˈoʊɹɪnstʃˌaɪlt θˈɔːt ðæt ˈɑːswəld,       #
        
        # if self.add_blank:                                #
            # text_norm = commons.intersperse(text_norm, 0) #
        
        text_norm = torch.LongTensor(text_norm)
        return text_norm

    # getitem method is called when you call dataset[index]
    def __getitem__(self, index):
        return self.get_audio_text_pair(self.audiopaths_and_text[index])
    # len method is called when you call len(dataset)
    def __len__(self):
        return len(self.audiopaths_and_text)
def spectrogram_torch(y, n_fft, sampling_rate, hop_size, win_size, center=False):
    # after normalizing, y should not be larger than 1 and smaller than -1.
    if torch.min(y) < -1.:
        print('min value is ', torch.min(y))
    if torch.max(y) > 1.:
        print('max value is ', torch.max(y))

    global hann_window
    dtype_device = str(y.dtype) + '_' + str(y.device)
    wnsize_dtype_device = str(win_size) + '_' + dtype_device
    if wnsize_dtype_device not in hann_window:
        # stores hann_window function values.
        # further examples will be in the next cell.
        hann_window[wnsize_dtype_device] = torch.hann_window(win_size).to(dtype=y.dtype, device=y.device)

    # padding, and will have further explanation in the next cell.
    y = torch.nn.functional.pad(y.unsqueeze(1), (int((n_fft-hop_size)/2), int((n_fft-hop_size)/2)), mode='reflect')
    y = y.squeeze(1)

    # Short-time Fourier transform (STFT). Converting audio to frequency domain.
    spec = torch.stft(y, n_fft, hop_length=hop_size, win_length=win_size, window=hann_window[wnsize_dtype_device],
                      center=center, pad_mode='reflect', normalized=False, onesided=True)
    # normalizing the spectrogram, and add 1e-6 in case of log(0)
    spec = torch.sqrt(spec.pow(2).sum(-1) + 1e-6)
    return spec

def load_wav_to_torch(full_path):
  sampling_rate, data = read(full_path)
  return torch.FloatTensor(data.astype(np.float32)), sampling_rate

# This method is to load data, it is obvious that
# we can divide audio and text by "|"
# since the data looked DUMMY1/LJ050-0234.wav|It has used...
def load_filepaths_and_text(filename, split="|"):
  with open(filename, encoding='utf-8') as f:
    filepaths_and_text = [line.strip().split(split) for line in f]
  return filepaths_and_text

def text_to_sequence(text, cleaner_names):
  '''Converts a string of text to a sequence of IDs corresponding to the symbols in the text.
    Args:
      text: string to convert to a sequence
      cleaner_names: names of the cleaner functions to run the text through
    Returns:
      List of integers corresponding to the symbols in the text
  '''
  sequence = []

  clean_text = _clean_text(text, cleaner_names)
  
  # convert cleaned text to sequence like [1, 3, 5]
  for symbol in clean_text:
    symbol_id = _symbol_to_id[symbol]
    sequence += [symbol_id] 
  return sequence
# function that called cleaner.
def _clean_text(text, cleaner_names):
  for name in cleaner_names:
    #cleaner = getattr(cleaners, name)
    #if not cleaner:
    #  raise Exception('Unknown cleaner: %s' % name)
    #text = cleaner(text)
    
    # call function by string: name
    cleaner = globals().get(name)
    
    # Check if the cleaner function exists
    if cleaner is None:
        raise Exception('Unknown cleaner: %s' % name)
    
    # Call the cleaner function with the text argument
    text = cleaner(text)
  return text

#### This TextAudioLoader will convert training data into this form:

#### (text, spectrogram, frequency domain)
##### Noted: text is not str, but a sequence like[1, 5, 3]

spectrogram and frequency domain are tensors with shape like (frequency, frames) and (frames).

In [5]:
train_dataset = TextAudioLoader([('audio/LJ001-0001.wav','Printing, in the only sense with which we are at present concerned, differs from most if not from all the arts and crafts represented in the Exhibition')])

In [6]:
train_dataset[0]

(tensor([ 58, 123, 156, 102,  56,  62, 102, 112,   3,  16, 102,  56,  81, 102,
          16, 156,  57, 135,  56,  54,  51,  16,  61, 156,  86,  56,  61,  16,
          65, 102,  81,  16,  65, 157, 102,  62, 131,  16,  65,  51, 158,  16,
          69, 158, 123,  16,  72,  62,  16,  58, 123, 156,  86,  68,  83,  56,
          62,  16,  53,  83,  56,  61, 156,  87, 158,  56,  46,   3,  16,  46,
         156, 102,  48,  85,  68,  16,  48, 123, 138,  55,  16,  55, 156,  57,
         135,  61,  62,  16, 102,  48,  16,  56, 157,  69, 158,  62,  16,  48,
         123, 138,  55,  16, 156,  76, 158,  54,  16,  81, 102,  16, 156,  69,
         158, 123,  62,  61,  16,  72,  56,  46,  16,  53, 123, 156,  72,  48,
          62,  61,  16, 123, 157,  86,  58, 123, 177,  68, 156,  86,  56,  62,
         177,  46,  16, 102,  56,  81, 102,  16,  86,  53,  61, 102,  44, 156,
         102, 131,  83,  56]),
 tensor([[0.0026, 0.0100, 0.0092,  ..., 0.0011, 0.0017, 0.0026],
         [0.0020, 0.0103, 0.0124,  

In [7]:
###############################collate_fn#################################
######################### For a better understanding of collate_fn here, check dataset.ipynb ###############################
class TextAudioCollate():
    def __init__(self, return_ids=False):
        self.return_ids = return_ids

    def __call__(self, batch):
        # Collate's training batch from normalized text and audio PARAMS #
        # ------                                                         #
        # batch: [text_normalized, spec_normalized, wav_normalized]      #
        # Right zero-pad all one-hot text sequences to max input length  #

        _, ids_sorted_decreasing = torch.sort(
            torch.LongTensor([x[1].size(1) for x in batch]),
            dim=0, descending=True)

        max_text_len = max([len(x[0]) for x in batch])
        max_spec_len = max([x[1].size(1) for x in batch])
        max_wav_len = max([x[2].size(1) for x in batch])

        text_lengths = torch.LongTensor(len(batch))
        spec_lengths = torch.LongTensor(len(batch))
        wav_lengths = torch.LongTensor(len(batch))

        text_padded = torch.LongTensor(len(batch), max_text_len)
        spec_padded = torch.FloatTensor(len(batch), batch[0][1].size(0), max_spec_len)
        wav_padded = torch.FloatTensor(len(batch), 1, max_wav_len)
        text_padded.zero_()
        spec_padded.zero_()
        wav_padded.zero_()
        for i in range(len(ids_sorted_decreasing)):
            row = batch[ids_sorted_decreasing[i]]

            text = row[0]
            text_padded[i, :text.size(0)] = text
            text_lengths[i] = text.size(0)

            spec = row[1]
            spec_padded[i, :, :spec.size(1)] = spec
            spec_lengths[i] = spec.size(1)

            wav = row[2]
            wav_padded[i, :, :wav.size(1)] = wav
            wav_lengths[i] = wav.size(1)

        if self.return_ids:
            return text_padded, text_lengths, spec_padded, spec_lengths, wav_padded, wav_lengths, ids_sorted_decreasing
        return text_padded, text_lengths, spec_padded, spec_lengths, wav_padded, wav_lengths

"""
In the context of deep learning, a collate function is a helper function used during the data loading process
specifically when creating batches for training or evaluation. The main purpose of a collate function is to organize and preprocess the input data
such as text and audio in this case, and format it into a suitable shape for the model to process. This often involves tasks like padding sequences
, sorting inputs by length, and creating tensors of the appropriate size.
"""

# We have our dataset train_dataset. Transform it into DataLoader with a collate function.
collate_fn = TextAudioCollate()
train_loader = DataLoader(train_dataset, collate_fn=collate_fn)

In [8]:
# access the train_loader
for batch in train_loader:
    text_padded, text_lengths, spec_padded, spec_lengths, wav_padded, wav_lengths = batch
    print("text_padded:", text_padded)
    print("text_lengths:", text_lengths)
    print("spec_padded:", spec_padded)
    print("spec_lengths:", spec_lengths)
    print("wav_padded:", wav_padded)
    print("wav_lengths:", wav_lengths)
    break

text_padded: tensor([[ 58, 123, 156, 102,  56,  62, 102, 112,   3,  16, 102,  56,  81, 102,
          16, 156,  57, 135,  56,  54,  51,  16,  61, 156,  86,  56,  61,  16,
          65, 102,  81,  16,  65, 157, 102,  62, 131,  16,  65,  51, 158,  16,
          69, 158, 123,  16,  72,  62,  16,  58, 123, 156,  86,  68,  83,  56,
          62,  16,  53,  83,  56,  61, 156,  87, 158,  56,  46,   3,  16,  46,
         156, 102,  48,  85,  68,  16,  48, 123, 138,  55,  16,  55, 156,  57,
         135,  61,  62,  16, 102,  48,  16,  56, 157,  69, 158,  62,  16,  48,
         123, 138,  55,  16, 156,  76, 158,  54,  16,  81, 102,  16, 156,  69,
         158, 123,  62,  61,  16,  72,  56,  46,  16,  53, 123, 156,  72,  48,
          62,  61,  16, 123, 157,  86,  58, 123, 177,  68, 156,  86,  56,  62,
         177,  46,  16, 102,  56,  81, 102,  16,  86,  53,  61, 102,  44, 156,
         102, 131,  83,  56]])
text_lengths: tensor([158])
spec_padded: tensor([[[0.0026, 0.0100, 0.0092,  ..., 0.0011

## Model Part

![model](./static/fig_1a.png)

In [9]:
"""
The following is the code of the model. A further explanation of the model can be found in models.ipynb.
"""
################# Go models.ipynb to see the implementation of SynthesizerTrn, the main model of VITS #################
from models import (
  SynthesizerTrn,
  MultiPeriodDiscriminator,
)
filter_length = 1024
segment_size = 8192
hop_length = 256
hps_model = {"inter_channels": 192,
    "hidden_channels": 192,
    "filter_channels": 768,
    "n_heads": 2,
    "n_layers": 6,
    "kernel_size": 3,
    "p_dropout": 0.1,
    "resblock": "1",
    "resblock_kernel_sizes": [3,7,11],
    "resblock_dilation_sizes": [[1,3,5], [1,3,5], [1,3,5]],
    "upsample_rates": [8,8,2,2],
    "upsample_initial_channel": 512,
    "upsample_kernel_sizes": [16,16,4,4],
    "n_layers_q": 3,
    "use_spectral_norm": False
  }
net_g = SynthesizerTrn(
      len(symbols),
      filter_length // 2 + 1,
      segment_size // hop_length,
      **hps_model)

In [10]:
for batch_idx, (x, x_lengths, spec, spec_lengths, y, y_lengths) in enumerate(train_loader):
    y_hat, l_length, attn, ids_slice, x_mask, z_mask,\
      (z, z_p, m_p, logs_p, m_q, logs_q) = net_g(x, x_lengths, spec, spec_lengths)
    print(y_hat.shape) # y_hat is wave front generated, its shape is (batch_size, 1, segment_size(8192 here))
    print(z.shape) # z is spectrogram
    print(l_length) # l_length is noise, shape is (batch size)
    print(attn.shape) # attention, shape is (batch size, 1, length of spectrogram, length of text)
    print(ids_slice) # random select a segment from the wave front
    # For example, the original shape of wave front is (batch size, 1, 200000), but it is too long, so we only choose a segment of it
    # here, it is 8192, so the y_hat.shape is (batch size, 1, 8192)

    print(x_mask.shape) # x_mask is used because the length of text is different, so we need to pad it to the same length
    # but the paded part is useless, like [2,50, 46, 26, 0, 0, 0], the mask will be [1,1,1,1,0,0,0]. We mask the zero part.
    print(z_mask.shape) # z_mask is the same as x_mask, but it is used for spectrogram.
    print("=====================================")
    print("(z, z_p, m_p, logs_p, m_q, logs_q) used to calculate loss")

0
315
0
315
0
315
0
315
0
315
0
315
0
315
0
315
0
315
0
315
0
315
0
315
torch.Size([1, 1, 8192])
torch.Size([1, 192, 831])
tensor([1.7941], grad_fn=<DivBackward0>)
torch.Size([1, 1, 831, 158])
tensor([700])
torch.Size([1, 1, 158])
torch.Size([1, 1, 831])
(z, z_p, m_p, logs_p, m_q, logs_q) used to calculate loss
